version: 2.1
jobs:
  build:
    working_directory: ~/prestation
    docker:
      - image: circleci/php:8.0.3-apache-node-browsers-legacy
        environments:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/db_test
      - image: circleci/mysql:5.7
        environments:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_test
    steps:
      - checkout
      - php/install-php:
          version: "8.0"
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev mariadb-client zlib1g-dev
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo docker-php-ext-enable zip pdo_mysql
      - run: sudo composer self-update
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
